# Site settings
title: py890000随笔 
email: py890000@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://py890000.github.io/" # the base hostname & protocol for your site
twitter_username: py890000
github_username:  py890000

# Build settings
markdown: kramdown
